### ISSUE TITLE
TypeError: csv_to_table() missing 1 required positional argument: 'delimiter'

### ISSUE THREAD

**Issue by gdubicki** [mplewis/csvtomd#13]
Hi, I am using latest released csvtomd, v. 0.2.0 from pypi on OS X with Python 3.5.2:

```
$ pip show csvtomd
Name: csvtomd
Version: 0.2.0
Summary: Convert your CSV files into Markdown tables.
Home-page: https://github.com/mplewis/csvtomd
Author: Matthew Lewis
Author-email: matt@mplewis.com
License: MIT
Location: /usr/local/lib/python3.5/site-packages
Requires:

$ which csvtomd
/usr/local/bin/csvtomd

$ head -n1 /usr/local/bin/csvtomd
#!/usr/local/opt/python3/bin/python3.5

$ /usr/local/opt/python3/bin/python3.5 --version
Python 3.5.2
```

..and it breaks when trying to use with:

```
$ csvtomd input.csv
Traceback (most recent call last):
  File "/usr/local/bin/csvtomd", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/csvtomd/csvtomd.py", line 136, in main
    table = csv_to_table(f)
TypeError: csv_to_table() missing 1 required positional argument: 'delimiter'
```

Please help.

**Comment by mplewis** [comment]
Sorry about that. Missed it when I was testing.

I've added a smoke test that would have caught that bug – [check it out on CircleCI](https://circleci.com/gh/mplewis/csvtomd/15).

**Comment by mplewis** [comment]
Release 0.2.1 has been pushed – update using pip and let me know if you have any issues. Thanks!
